# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-playground',
                'doc_host': 'https://klima7.github.io',
                'git_url': 'https://github.com/klima7/nbdev-playground',
                'lib_path': 'nbdev_playground'},
  'syms': {'nbdev_playground.core': {'nbdev_playground.core.foo': ('core.html#foo', 'nbdev_playground/core.py')}}}
